testing

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,44 +1,44 @@
 #!/bin/bash
 
-# STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")
 
-# if [[ "$STAGED_FILES" = "" ]]; then
-#   exit 0
-# fi
+if [[ "$STAGED_FILES" = "" ]]; then
+  exit 0
+fi
 
-# PASS=true
+PASS=true
 
-# echo "\nValidating PHPCS:\n"
+echo "\nValidating PHPCS:\n"
 
-# # # Check for phpcs
-# which ./vendor/bin/phpcs &> /dev/null
-# if [[ "$?" == 1 ]]; then
-#   echo "\t\033[41mPlease install PHPCS\033[0m"
-#   exit 1
-# fi
+# # Check for phpcs
+which ./vendor/bin/phpcs &> /dev/null
+if [[ "$?" == 1 ]]; then
+  echo "\t\033[41mPlease install PHPCS\033[0m"
+  exit 1
+fi
 
-# RULESET=./phpcs.xml
+RULESET=./phpcs.xml
 
-# for FILE in $STAGED_FILES
-# do
-#   ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit --standard="$RULESET" "$FILE"
+for FILE in $STAGED_FILES
+do
+  ./vendor/bin/phpcs --runtime-set ignore_warnings_on_exit --standard="$RULESET" "$FILE"
 
-#   if [[ "$?" == 0 ]]; then
-#     echo "\t\033[32mPHPCS Passed: $FILE\033[0m"
-#   else
-#     echo "\t\033[41mPHPCS Failed: $FILE\033[0m"
-#     PASS=false
-#   fi
-# done
+  if [[ "$?" == 0 ]]; then
+    echo "\t\033[32mPHPCS Passed: $FILE\033[0m"
+  else
+    echo "\t\033[41mPHPCS Failed: $FILE\033[0m"
+    PASS=false
+  fi
+done
 
-# echo "\nPHPCS validation completed!\n"
+echo "\nPHPCS validation completed!\n"
 
-# if ! $PASS; then
-#   echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass PHPCS but do not. Please fix the PHPCS errors and try again.\n"
-#   exit 1
-# else
-#   echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
-# fi
+if ! $PASS; then
+  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass PHPCS but do not. Please fix the PHPCS errors and try again.\n"
+  exit 1
+else
+  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
+fi
 
 # Run Prettier against staged files.
 
